import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const policy = readFileSync(resolve(root, 'src/response-policy.md'), 'utf8').trim();
if (!policy || policy.length > 9000) throw new Error('Policy must contain 1–9000 characters');
const skill = `---\nname: skip-echo\ndescription: Reduce unnecessary repetition in multi-turn user-facing explanations and progress reports. Apply to follow-up questions, added constraints, corrections, and ongoing status updates. Preserve complete answers, full deliverables, and requests for re-explanation.\n---\n\n# SkipEcho\n\n${policy}\n`;
const outputs = new Map([
 ['SKILL.md', skill],
 ['skills/skip-echo/SKILL.md', skill],
 ['scripts/policy.generated.mjs', '// Generated by scripts/build.mjs. Do not edit.\nexport default '+JSON.stringify(policy)+';\n']
]);
for (const [path, text] of outputs) {
 const full = resolve(root, path);
 if (process.argv.includes('--check')) {
  if (readFileSync(full, 'utf8') !== text) throw new Error(`Stale generated file: ${path}`);
 } else { mkdirSync(dirname(full), {recursive:true}); writeFileSync(full, text); }
}
