import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, relative, join } from 'node:path';
import { nativeEvalFiles, conditionEvalFiles, NATIVE_DIR, CONDITIONS_DIR } from './native-evals.mjs';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const policy = readFileSync(resolve(root, 'src/response-policy.md'), 'utf8').trim();
if (!policy || policy.length > 9000) throw new Error('Policy must contain 1–9000 characters');
const description = 'Avoid re-explaining what was already said in multi-turn conversations and long agent sessions. Use for follow-up questions, added constraints, corrections, small revisions to existing code or documents, and ongoing progress or status reports. Keeps complete answers when full text, copy-ready output, recaps, handoffs, or re-explanations are requested. Removes repeated claims, not words, so it can be combined with terse styles.';
const skill = `---\nname: skip-echo\ndescription: ${description}\nargument-hint: "[on|off|full]"\n---\n\n# SkipEcho\n\n${policy}\n`;
const cursor = `---\ndescription: SkipEcho response policy. Avoid re-explaining unchanged context while keeping complete answers.\nalwaysApply: true\n---\n\n${policy}\n`;
const agents = `<!-- Generated by scripts/build.mjs from src/response-policy.md. Paste this section into your AGENTS.md. -->\n## Response policy: SkipEcho\n\n${policy}\n`;
const outputs = new Map([
 ['SKILL.md', skill],
 ['skills/skip-echo/SKILL.md', skill],
 ['scripts/policy.generated.mjs', '// Generated by scripts/build.mjs. Do not edit.\nexport default '+JSON.stringify(policy)+';\n'],
 ['integrations/cursor/skip-echo.mdc', cursor],
 ['integrations/AGENTS.md', agents],
 ...nativeEvalFiles(root),
 ...conditionEvalFiles(root)
]);
const check = process.argv.includes('--check');
// Generated eval suites must match the frozen sources exactly; stale case files are errors.
const listFiles = (dir, top) => existsSync(dir) ? readdirSync(dir, { withFileTypes: true }).flatMap(e => e.name === 'results' && dir === top ? [] : e.isDirectory() ? listFiles(join(dir, e.name), top) : [join(dir, e.name)]) : [];
for (const suite of [NATIVE_DIR, CONDITIONS_DIR]) {
 const top = resolve(root, suite);
 for (const file of listFiles(top, top)) {
  const rel = relative(root, file).split('\\').join('/');
  if (outputs.has(rel)) continue;
  // `claude plugin eval` copies the replayed history next to each case as <session-id>.jsonl; they are gitignored.
  if (/\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.jsonl$/.test(rel)) continue;
  if (check) throw new Error(`Unexpected file in generated eval suite: ${rel}`);
  rmSync(file);
 }
}
for (const [path, text] of outputs) {
 const full = resolve(root, path);
 if (check) {
  if (!existsSync(full) || readFileSync(full, 'utf8') !== text) throw new Error(`Stale generated file: ${path}`);
 } else { mkdirSync(dirname(full), {recursive:true}); writeFileSync(full, text); }
}
